vehicle:
    resource: "@VehicleBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

show_vehicles:
    pattern: /showVehicles/{page}
    defaults: {_controller: VehicleBundle:Main:showVehicles, page: 1}


