# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    validator.start_greater_than_default:
        class: VehicleBundle\Validator\Constraints\StartGreaterThanDefaultValidator
        tags:
            - { name: validator.constraint_validator }

    vehicle.locale_listener:
        class: VehicleBundle\EventListener\LocaleListener
        arguments: ['%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber }