<?php

namespace VehicleBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MakeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MakeRepository extends EntityRepository
{
}
