<?php

namespace VehicleBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RefuelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefuelRepository extends EntityRepository
{
}
